use num_enum::TryFromPrimitive;

#[derive(Debug, PartialEq, Eq, Clone, Copy, TryFromPrimitive)]
#[repr(u8)]
pub enum External {
	CaptainFalcon = 0,
	DonkeyKong = 1,
	Fox = 2,
	GameAndWatch = 3,
	Kirby = 4,
	Bowser = 5,
	Link = 6,
	Luigi = 7,
	Mario = 8,
	Marth = 9,
	Mewtwo = 10,
	Ness = 11,
	Peach = 12,
	Pikachu = 13,
	IceClimbers = 14,
	Jigglypuff = 15,
	Samus = 16,
	Yoshi = 17,
	Zelda = 18,
	Sheik = 19,
	Falco = 20,
	YoungLink = 21,
	DrMario = 22,
	Roy = 23,
	Pichu = 24,
	Ganondorf = 25,
	MasterHand = 26,
	WireFrameMale = 27,
	WireFrameFemale = 28,
	GigaBowser = 29,
	CrazyHand = 30,
	Sandbag = 31,
	Popo = 32,
}

#[derive(Debug, PartialEq, Eq, Clone, Copy, TryFromPrimitive)]
#[repr(u8)]
pub enum Internal {
	Mario = 0,
	Fox = 1,
	CaptainFalcon = 2,
	DonkeyKong = 3,
	Kirby = 4,
	Bowser = 5,
	Link = 6,
	Sheik = 7,
	Ness = 8,
	Peach = 9,
	Popo = 10,
	Nana = 11,
	Pikachu = 12,
	Samus = 13,
	Yoshi = 14,
	Jigglypuff = 15,
	Mewtwo = 16,
	Luigi = 17,
	Marth = 18,
	Zelda = 19,
	YoungLink = 20,
	DrMario = 21,
	Falco = 22,
	Pichu = 23,
	GameAndWatch = 24,
	Ganondorf = 25,
	Roy = 26,
	MasterHand = 27,
	CrazyHand = 28,
	WireFrameMale = 29,
	WireFrameFemale = 30,
	GigaBowser = 31,
	Sandbag = 32,
}
